---
title: Gnaneshwara Babu
date: 2022-05-25
---

theme: minima
title: Gnaneshwara Babu
author: Gnaneshwara Babu
email: mail2gnana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Gnaneshwara Babu and I live in Sydney, Australia. I am facinated about everything in cloud, and various things in technology. 
  
  
  

# social links
twitter_username: mail2gnana # DO NOT include the @ character, or else the build will fail!
github_username:  code2gnana # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
